const hash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(b=>b.toString(16).padStart(2,'0')).join('');
const getAccounts=()=>{const accounts=JSON.parse(localStorage.getItem('masjidPointActivatedAccounts')||'[]'),legacy=JSON.parse(localStorage.getItem('masjidPointActivatedAccount')||'null');if(legacy?.verified&&!accounts.some(a=>String(a.email).toLowerCase()===String(legacy.email).toLowerCase()))accounts.push(legacy);return accounts};
const saveAccounts=items=>localStorage.setItem('masjidPointActivatedAccounts',JSON.stringify(items));
const forgot=document.createElement('a');forgot.href='forgot-password';forgot.className='forgot-password-link';forgot.textContent='Forgot your password?';document.querySelector('#login-form .button').before(forgot);const forgotStyle=document.createElement('link');forgotStyle.rel='stylesheet';forgotStyle.href='password-email.css';document.head.appendChild(forgotStyle);
document.querySelector('#login-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget),email=String(data.get('email')).trim().toLowerCase(),passwordHash=await hash(String(data.get('password'))),account=getAccounts().find(a=>String(a.email).toLowerCase()===email&&a.verified);
  // Individuals live in their own collection, so try that before masjid/business accounts.
  if(!account){try{const response=await fetch('/api/customer/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,passwordHash})});if(response.ok){const {customer}=await response.json();sessionStorage.setItem('masjidPointSession',JSON.stringify({role:'customer',customerId:customer.id,email:customer.email,name:customer.name,signedInAt:new Date().toISOString()}));location.href=new URLSearchParams(location.search).get('return')||'my-account';return}}catch(_){}}
  const error=document.querySelector('#login-error');if(!account?.passwordHash){error.textContent=account?'This older account needs a one-time local password setup below.':'No activated account matches this email.';error.hidden=false;return}if(account.passwordHash!==passwordHash){error.textContent='The password is incorrect.';error.hidden=false;return}const state=await MasjidDB.state(),application=(state.masjidPointAdminApplications||[]).find(a=>a.reference===account.reference);if(['blocked','deactivated'].includes(application?.accountStatus)){error.textContent=application.accountStatus==='blocked'?'This account has been blocked by the administrator.':'This account has been deactivated. Contact the administrator to restore access.';error.hidden=false;return}const role=application?.type==='business'?'business':'masjid';sessionStorage.setItem('masjidPointSession',JSON.stringify({role,reference:account.reference,email:account.email,signedInAt:new Date().toISOString()}));location.href=new URLSearchParams(location.search).get('return')||(role==='business'?'business-portal':'masjid-portal')};
document.querySelector('#setup-password').onclick=()=>{const email=document.querySelector('#login-form').elements.email.value;document.querySelector('#login-form').hidden=true;document.querySelector('#setup-form').hidden=false;if(email)document.querySelector('#setup-form').elements.email.value=email};document.querySelector('#back-login').onclick=()=>{document.querySelector('#setup-form').hidden=true;document.querySelector('#login-form').hidden=false};
document.querySelector('#setup-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget),reference=String(data.get('reference')).trim().toUpperCase(),email=String(data.get('email')).trim().toLowerCase(),password=String(data.get('password')),confirm=String(data.get('confirm')),state=await MasjidDB.state(),application=(state.masjidPointAdminApplications||[]).find(a=>a.reference===reference&&['approved','activated'].includes(a.status));const error=document.querySelector('#setup-error');if(!application){error.textContent='No approved masjid application matches this reference.';error.hidden=false;return}if(application.email!=='Registered contact email'&&String(application.email).toLowerCase()!==email){error.textContent='The registered email does not match.';error.hidden=false;return}if(password!==confirm){error.textContent='The passwords do not match.';error.hidden=false;return}const accounts=getAccounts().filter(a=>a.reference!==reference);accounts.unshift({reference,email,verified:true,activatedAt:application.activatedAt||new Date().toISOString(),passwordHash:await hash(password)});saveAccounts(accounts);error.hidden=true;document.querySelector('#setup-form').hidden=true;document.querySelector('#login-form').hidden=false;document.querySelector('#login-form').elements.email.value=email;alert('Password saved. You can now sign in.')};
