(function(){
  const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(n)||0);
  const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function panel(title,intro){const s=document.createElement('section');s.id='workflow';s.className='workflow-panel';s.innerHTML=`<header><div><p class="eyebrow"><span></span> Connected local database</p><h2>${title}</h2><p>${intro}</p></div><button class="workflow-refresh" type="button">Refresh</button></header><div class="workflow-body">Loading…</div>`;s.querySelector('button').onclick=()=>location.reload();return s}
  async function business(){const host=document.querySelector('.business-content');if(!host)return;const box=panel('Job approval and payment flow','Approved mosque charges appear here. A job becomes public only after admin verifies the payment.');host.prepend(box);const state=await MasjidDB.state(),account=state.masjidPointFinance.accounts.find(a=>a.code==='BUS-00184'),invoices=(account?.invoices||[]).filter(i=>i.workflow),jobs=state.masjidPointJobs||[];box.querySelector('.workflow-body').innerHTML=jobs.length?jobs.map(j=>`<article><div><strong>${esc(j.title)}</strong><small>${j.id}</small></div><div class="workflow-steps">${j.masjids.map(m=>`<span class="${m.status==='approved'?'done':''}">${esc(m.name)}: ${m.status}${m.status==='approved'?` · ${m.paymentStatus} · ${money(m.fee)}`:''}</span>`).join('')}</div></article>`).join(''):'<p>No job submissions yet.</p>';if(invoices.length){const invoice=invoices[0],proof=(state.masjidPointPaymentProofs||[]).slice().reverse().find(p=>p.invoice===invoice.number&&p.status!=='rejected');box.querySelector('.workflow-body').insertAdjacentHTML('beforeend',`<article class="workflow-invoice"><div><strong>${invoice.number}</strong><small>Job-listing invoice · ${money(invoice.amount-invoice.paid)} due</small></div><button class="button" id="pay-workflow" ${proof?'disabled':''}>${proof?'Proof awaiting admin review':'Submit bank-transfer proof'}</button></article>`);const b=box.querySelector('#pay-workflow');if(b&&!b.disabled)b.onclick=()=>{const modal=document.querySelector('#proof-modal'),form=document.querySelector('#proof-form');form.reset();form.elements.invoice.value=invoice.number;form.elements.amount.value=(invoice.amount-invoice.paid).toFixed(2);form.elements.date.value=new Date().toISOString().slice(0,10);document.querySelector('#proof-invoice-number').textContent=invoice.number;document.querySelector('#proof-file-name').textContent='Choose payment evidence';modal.hidden=false}}
  }
  async function masjid(){const host=document.querySelector('.portal-content');if(!host)return;const box=panel('Revenue and settlement status','You receive 70% of each verified job-listing payment. Admin sends the bank transfer and records it here.');host.append(box);const state=await MasjidDB.state(),name='Central Masjid',finance=state.masjidPointFinance,paid=(state.masjidPointJobs||[]).flatMap(j=>j.masjids.filter(m=>m.name===name&&m.paymentStatus==='paid').map(m=>({title:j.title,...m}))),history=(finance.settlementHistory||[]).filter(s=>s.masjid===name),settledIds=new Set(history.map(s=>s.jobId));box.querySelector('.workflow-body').innerHTML=paid.length?paid.map(m=>`<article><div><strong>${esc(m.title)}</strong><small>Business paid ${money(m.fee)}</small></div><span class="workflow-state ${settledIds.has(m.jobId)?'paid':'due'}">${settledIds.has(m.jobId)?'Settlement paid':`${money(m.fee*.7)} due from admin`}</span></article>`).join(''):'<p>No verified job payments yet.</p>'}
  async function admin(){const host=document.querySelector('.dashboard-content');if(!host)return;const box=panel('Business payments to mosque settlements','Verify business payment evidence first, then transfer each mosque’s 70% share and mark it settled.');host.append(box);const state=await MasjidDB.state(),finance=state.masjidPointFinance,history=finance.settlementHistory||[],rows=[];(state.masjidPointJobs||[]).forEach(j=>j.masjids.filter(m=>m.paymentStatus==='paid').forEach(m=>{const done=history.some(s=>s.jobId===j.id&&s.masjid===m.name);rows.push({job:j,choice:m,done})}));box.querySelector('.workflow-body').innerHTML=rows.length?rows.map(r=>`<article><div><strong>${esc(r.choice.name)}</strong><small>${esc(r.job.title)} · received ${money(r.choice.fee)}</small></div>${r.done?'<span class="workflow-state paid">Paid to mosque</span>':`<button class="button" data-workflow-settle="${esc(r.choice.name)}">Send ${money(r.choice.fee*.7)} settlement</button>`}</article>`).join(''):'<p>No mosque settlements are due yet.</p>';box.querySelectorAll('[data-workflow-settle]').forEach(b=>b.onclick=async()=>{b.disabled=true;const response=await fetch('/api/settle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({masjid:b.dataset.workflowSettle})});const result=await response.json();if(!response.ok){alert(result.error);b.disabled=false;return}location.reload()})}
  const start=()=>document.body.classList.contains('payments-page')?null:document.body.classList.contains('portal-page')?masjid():document.body.classList.contains('business-page')&&!document.body.classList.contains('jobs-page')?business():null;
  MasjidDB.ready.then(start);
})();
