const {spawn}=require('child_process'),path=require('path'),edge='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',port=9897,base='http://127.0.0.1:4174',sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));let browser,ws,id=0,pending=new Map(),exceptions=[];
async function connect(){for(let attempt=0;attempt<60;attempt++){try{const pages=await fetch(`http://127.0.0.1:${port}/json/list`).then(response=>response.json()),page=pages.find(item=>item.type==='page');if(page){ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject});ws.onmessage=event=>{const message=JSON.parse(event.data);if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails.text);const callback=pending.get(message.id);if(callback){pending.delete(message.id);callback(message.result)}};return}}catch(_){}await sleep(200)}throw Error('Could not connect to Edge')}
const cdp=(method,params={})=>new Promise(resolve=>{pending.set(++id,resolve);ws.send(JSON.stringify({id,method,params}))});
async function evaluate(expression){const response=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});return response.result.value}
async function go(url){exceptions=[];await cdp('Page.navigate',{url});await sleep(1700)}
function assert(value,message){if(!value)throw Error(message)}
(async()=>{browser=spawn(edge,['--headless=new',`--remote-debugging-port=${port}`,`--user-data-dir=${path.join(__dirname,'.admin-portal-edge-'+Date.now())}`,'--no-first-run','about:blank'],{stdio:'ignore'});await connect();await cdp('Page.enable');await cdp('Runtime.enable');
 await go(`${base}/admin-login.html`);await evaluate(`document.querySelector('#admin-email').value='admin@masjidpoint.co.uk';document.querySelector('#admin-password').value='Admin!2026Secure';document.querySelector('#admin-login-form').requestSubmit()`);await sleep(1500);assert((await evaluate('location.pathname')).match(/\/admin(?:\.html)?$/),'Admin login failed');
 const pages=['admin.html','admin-applications.html','admin-masjids.html','admin-businesses.html','admin-masjid-products.html','admin-invoices.html','admin-payments.html','admin-bank-settings.html','admin-users.html','admin-audit.html'];
 for(const page of pages){await go(`${base}/${page}`);const result=await evaluate(`({path:location.pathname,title:document.title,nav:document.querySelectorAll('.admin-sidebar nav a').length,active:document.querySelectorAll('.admin-sidebar nav a.active').length,logout:!!document.querySelector('#admin-logout'),notification:!!document.querySelector('.notification-centre'),heading:document.querySelector('.admin-main h1')?.textContent.trim()})`);assert(result.path.endsWith('/'+page),`${page} redirected to ${result.path}`);assert(result.nav>=8,`${page} has incomplete navigation`);assert(result.active===1,`${page} does not have exactly one active navigation item`);assert(result.logout,`${page} is missing logout`);assert(result.notification,`${page} is missing notifications`);assert(result.heading,`${page} is missing its heading`);assert(!exceptions.length,`${page} raised browser error: ${exceptions.join(', ')}`)}
 await go(`${base}/admin-masjid-products.html`);assert(await evaluate(`document.querySelectorAll('[data-edit-product]').length>0&&document.querySelectorAll('[data-delete-product]').length>0`),'Product edit/delete controls are missing');
 await go(`${base}/admin-applications.html`);assert(await evaluate(`document.querySelectorAll('.native-admin-pager').length===1`),'Applications pagination is missing');
 assert(await evaluate(`[...document.querySelectorAll('#application-rows tr')].every(row=>row.classList.contains('admin-clickable-surface')&&row.tabIndex===0)`),'Application rows are not fully navigable');
 assert(await evaluate(`document.querySelector('[data-status="pending"]').classList.contains('active')`),'Applications does not default to Pending');await go(`${base}/admin-masjids.html`);assert(await evaluate(`document.querySelector('[data-status="approved"]').classList.contains('active')`),'Masjids does not default to Approved');await go(`${base}/admin-businesses.html`);assert(await evaluate(`document.querySelector('[data-status="approved"]').classList.contains('active')`),'Businesses does not default to Approved');
 await go(`${base}/admin-audit.html`);assert(await evaluate(`!!document.querySelector('#audit-search')&&!!document.querySelector('#audit-next')`),'Audit controls are missing');
 const state=await fetch(`${base}/api/state`).then(response=>response.json()),pendingMosque=(state.masjidPointAdminApplications||[]).find(item=>item.type==='masjid'&&item.status==='pending');if(pendingMosque){await go(`${base}/admin-masjid-view.html?reference=${encodeURIComponent(pendingMosque.reference)}`);const gate=await evaluate(`({pricing:!document.querySelector('.masjid-view-grid>aside')?.hidden,shop:!!document.querySelector('.masjid-operational-actions'),finance:[...document.querySelectorAll('.view-card h2')].some(h=>h.textContent.toLowerCase().includes('payments and settlements')),qr:[...document.querySelectorAll('.view-card h2')].some(h=>h.textContent.toLowerCase().includes('advertising qr')),products:!!document.querySelector('.mosque-profile-products'),notice:!!document.querySelector('.pending-access-notice')})`);assert(!gate.pricing&&!gate.shop&&!gate.finance&&!gate.qr&&!gate.products&&gate.notice,'Pending mosque can see operational controls')}
 const populated=state.masjidPointAdminApplications.find(item=>item.reference==='MSJ-2026-DD7PXK');if(populated){await go(`${base}/admin-masjid-view.html?reference=MSJ-2026-DD7PXK`);const profile=await evaluate(`({products:document.querySelectorAll('.mosque-profile-product').length,jobs:[...document.querySelectorAll('.profile-listing-row')].filter(row=>row.closest('section')?.querySelector('h3')?.textContent.includes('Job')).length,adverts:[...document.querySelectorAll('.profile-listing-row')].filter(row=>row.closest('section')?.querySelector('h3')?.textContent.includes('Business')).length,invoiceText:document.body.textContent.includes('INV-2026-'),financeStatuses:[...document.querySelectorAll('.finance-workflow-status')].map(item=>item.textContent.trim()),listingStatuses:[...document.querySelectorAll('.payment-label')].map(item=>item.textContent.trim()),summaryLabels:[...document.querySelectorAll('.listing-summary small')].map(item=>item.textContent.trim())})`);assert(profile.products===3&&profile.jobs>=2&&profile.adverts>=1&&profile.invoiceText&&profile.financeStatuses.includes('Awaiting business payment')&&profile.financeStatuses.includes('Business payment verified')&&profile.listingStatuses.includes('Awaiting business payment')&&profile.listingStatuses.includes('Business payment verified')&&profile.summaryLabels.includes('Awaiting business payment')&&profile.summaryLabels.includes('Awaiting mosque decision'),'Activated mosque profile data is incomplete')}
 if(populated){const productFilter=await evaluate(`(()=>{const cards=[...document.querySelectorAll('.mosque-product-summary article')],visibleCard=cards[1],expected=Number(visibleCard.querySelector('strong').textContent);visibleCard.click();return{active:visibleCard.classList.contains('active-filter'),expected,shown:[...document.querySelectorAll('.mosque-profile-product')].filter(item=>!item.hidden).length,ordersRole:cards[3].getAttribute('role')}})()`);assert(productFilter.active&&productFilter.shown===productFilter.expected&&productFilter.ordersRole==='button','Mosque product summary filters are incomplete')}
 let financeFilter;if(populated){financeFilter=await evaluate(`(()=>{const card=[...document.querySelectorAll('.view-card')].find(item=>item.querySelector('h2')?.textContent.includes('Mosque payments')),cards=[...card.querySelectorAll('.finance-summary>div')],due=Number(cards[1].querySelector('strong').textContent.replace(/[^0-9.-]/g,''));cards[1].click();const visible=[...card.querySelectorAll('.profile-finance-table:first-of-type tbody tr')].filter(row=>!row.hidden);return{active:cards[1].classList.contains('active-filter'),due,settle:!!cards[1].querySelector('.profile-settlement-action'),onlyVerified:visible.every(row=>!!row.querySelector('.finance-workflow-status.verified-payment'))}})()`);assert(financeFilter.active&&financeFilter.onlyVerified&&(financeFilter.due>0?financeFilter.settle:true),'Mosque finance cards or profile settlement action are incomplete')}
 if(populated&&financeFilter.due>0){await evaluate(`document.querySelector('.profile-settlement-action').click()`);const settlementForm=await evaluate(`({open:!document.querySelector('#profile-settlement-modal').hidden,mosque:document.querySelector('#profile-settlement-mosque').textContent,amount:document.querySelector('#profile-settlement-amount').textContent,required:document.querySelector('#profile-settlement-modal [name=transactionReference]').required,evidenceRequired:document.querySelector('#profile-settlement-modal [name=evidence]').required,evidenceTypes:document.querySelector('#profile-settlement-modal [name=evidence]').accept})`);assert(settlementForm.open&&settlementForm.mosque.includes('Frontend Test Masjid')&&settlementForm.amount.includes(financeFilter.due.toFixed(2))&&settlementForm.required&&!settlementForm.evidenceRequired&&settlementForm.evidenceTypes.includes('application/pdf'),'Profile settlement form or optional evidence upload is incomplete')}
 if(populated){await go(`${base}/admin-masjid-view.html?reference=MSJ-2026-DD7PXK`);const filterCheck=await evaluate(`(()=>{const cards=[...document.querySelectorAll('.listing-summary article')],target=cards.find(card=>Number(card.querySelector('strong').textContent)>0),expected=Number(target.querySelector('strong').textContent);target.click();return{active:target.classList.contains('active-filter'),expected,visible:[...document.querySelectorAll('.profile-listing-row')].filter(row=>!row.hidden&&!row.closest('section').hidden).length}})()`);assert(filterCheck.active&&filterCheck.visible===filterCheck.expected,'Mosque listing summary filter does not match its count')}
 const demoProof=(state.masjidPointPaymentProofs||[]).find(item=>item.id==='PAY-DEMO-217765');if(demoProof){await go(`${base}/admin-payments.html?proof=${demoProof.id}#proofs`);assert(await evaluate(`!!document.querySelector('[data-proof="PAY-DEMO-217765"]')`),'Demo payment proof is missing from admin queue');await evaluate(`document.querySelector('[data-proof="PAY-DEMO-217765"]').click()`);await sleep(500);assert(await evaluate(`!document.querySelector('#proof-review').hidden&&document.querySelector('#proof-preview img')?.src.includes('test-payment-proof-217765.svg')`),'Demo payment evidence preview did not open')}
 if(demoProof){await go(`${base}/admin-invoice-view.html?code=BUS-02033&invoice=INV-2026-217765`);const invoiceProof=await evaluate(`({panel:!!document.querySelector('.invoice-proof-panel'),amount:document.querySelector('.invoice-proof-title strong')?.textContent,evidence:document.querySelector('.invoice-proof-preview img')?.src,status:document.querySelector('.proof-state')?.textContent.trim(),review:document.querySelector('.invoice-proof-details .button')?.dataset.reviewInvoiceProof})`);assert(invoiceProof.panel&&invoiceProof.amount.includes('25.00')&&invoiceProof.evidence.includes('test-payment-proof-217765.svg')&&invoiceProof.status===demoProof.status&&invoiceProof.review==='PAY-DEMO-217765','Invoice payment evidence section is incomplete');await evaluate(`document.querySelector('.invoice-proof-details .button').click()`);await sleep(300);const popup=await evaluate(`({open:!document.querySelector('.invoice-proof-modal').hidden,title:document.querySelector('#invoice-proof-modal-title')?.textContent,image:document.querySelector('#invoice-proof-modal-preview img')?.src,approve:!document.querySelector('#invoice-approve-proof').hidden,reject:!document.querySelector('#invoice-reject-proof').hidden})`);assert(popup.open&&popup.title.includes('INV-2026-217765')&&popup.image.includes('test-payment-proof-217765.svg')&&(demoProof.status==='submitted'?(popup.approve&&popup.reject):(!popup.approve&&!popup.reject)),'Invoice proof-review popup is incomplete')}
 console.log('PASS complete admin portal frontend audit');
})().catch(error=>{console.error('FAIL',error.message);process.exitCode=1}).finally(()=>{try{ws.close()}catch(_){}try{browser.kill()}catch(_){}});
