const ADMIN_PASSWORD = require('../scripts/seed-demo-data.js').ADMIN_PASSWORD;
const {spawn}=require('child_process'),path=require('path'),edge='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',port=9891,base='http://127.0.0.1:4174',sleep=ms=>new Promise(r=>setTimeout(r,ms));let browser,ws,id=0,pending=new Map();
async function connect(){for(let i=0;i<50;i++){try{const pages=await fetch(`http://127.0.0.1:${port}/json/list`).then(r=>r.json()),page=pages.find(x=>x.type==='page');if(page){ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject});ws.onmessage=e=>{const m=JSON.parse(e.data),p=pending.get(m.id);if(p){pending.delete(m.id);p(m.result)}};return}}catch(_){}await sleep(200)}throw Error('Could not connect to Edge')}
const cdp=(method,params={})=>new Promise(resolve=>{pending.set(++id,resolve);ws.send(JSON.stringify({id,method,params}))});
async function ev(expression){return(await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value}
async function go(url){await cdp('Page.navigate',{url});await sleep(1300)}
function assert(value,message){if(!value)throw Error(message)}
(async()=>{browser=spawn(edge,['--headless=new',`--remote-debugging-port=${port}`,`--user-data-dir=${path.join(__dirname,'.admin-auth-edge-'+Date.now())}`,'--no-first-run','about:blank'],{stdio:'ignore'});await connect();await cdp('Page.enable');
  await go(`${base}/admin-invoices.html`);let result=await ev(`({path:location.pathname,returnValue:new URLSearchParams(location.search).get('return')})`);assert(result.path.match(/\/admin-login(?:\.html)?$/),'Direct admin access was not blocked');assert(result.returnValue==='admin-invoices','Original destination was not preserved');
  await ev(`document.querySelector('#admin-email').value='wrong@example.test';document.querySelector('#admin-password').value='wrong';document.querySelector('#admin-login-form').requestSubmit()`);await sleep(250);assert(await ev(`!document.querySelector('#admin-login-error').hidden`),'Wrong-password error did not appear');
  await ev(`document.querySelector('#admin-email').value='admin@masjidpoint.co.uk';document.querySelector('#admin-password').value=${JSON.stringify(ADMIN_PASSWORD)};document.querySelector('#admin-login-form').requestSubmit()`);await sleep(1700);assert((await ev(`location.pathname`)).match(/\/admin-invoices(?:\.html)?$/),'Login did not return to requested admin page');
  assert(await ev(`!!document.querySelector('#admin-logout')`),'Logout control is missing');await ev(`document.querySelector('#admin-logout').click()`);await sleep(900);assert((await ev(`location.pathname`)).match(/\/admin-login(?:\.html)?$/),'Logout did not return to login');
  await go(`${base}/admin-businesses.html`);assert((await ev(`location.pathname`)).match(/\/admin-login(?:\.html)?$/),'Logged-out admin route remained accessible');console.log('PASS admin authentication frontend journey');
})().catch(error=>{console.error('FAIL',error.message);process.exitCode=1}).finally(()=>{try{ws.close()}catch(_){}try{browser.kill()}catch(_){}});
