const {spawn}=require('child_process');const path=require('path');
const edge='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',port=9333,base='http://127.0.0.1:4174';
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),assert=(v,m)=>{if(!v)throw new Error(m)};let seq=0,pending=new Map(),ws,browser;
async function connect(){for(let i=0;i<30;i++){try{const tabs=await fetch(`http://127.0.0.1:${port}/json/list`).then(r=>r.json()),tab=tabs.find(t=>t.type==='page');if(tab){ws=new WebSocket(tab.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const {resolve,reject}=pending.get(m.id);pending.delete(m.id);m.error?reject(new Error(m.error.message)):resolve(m.result)}};return}}catch{}await sleep(200)}throw new Error('Could not connect to Edge')}
function cdp(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))})}
async function evaluate(expression){const r=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||'Browser expression failed');return r.result.value}
async function go(url,wait=1800){await cdp('Page.navigate',{url});await sleep(wait)}
const set=(name,value)=>evaluate(`(()=>{const e=document.querySelector('[name=${JSON.stringify(name)}]');if(!e)throw Error('Missing ${name}');e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))})()`);
const click=selector=>evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing ${selector}');e.click()})()`);
(async()=>{const stamp=Date.now().toString().slice(-6),name=`Frontend Test Masjid ${stamp}`,email=`frontend.masjid.${stamp}@example.test`,password=`Frontend!${stamp}Aa`,profile=path.join(__dirname,`.edge-profile-${stamp}`);browser=spawn(edge,['--headless=new',`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'--no-first-run','--disable-gpu','about:blank'],{stdio:'ignore'});await connect();await cdp('Page.enable');await cdp('Runtime.enable');
  await go(`${base}/register-masjid.html`,2200);await set('masjidName',name);await set('address1','10 Frontend Test Road');await set('city','Birmingham');await set('postcode','B12 0XS');await set('masjidPhone','0121 555 0101');await click('#next-button');await set('contactName','Frontend Tester');await set('role','Trustee');await set('contactPhone','07123 456789');await set('email',email);await click('#next-button');await evaluate(`document.querySelector('[name=authority]').checked=true;document.querySelector('[name=consent]').checked=true`);await click('#next-button');await sleep(600);const reference=await evaluate(`document.querySelector('#reference-number').textContent`);assert(reference.startsWith('MSJ-'),'Frontend registration did not return a reference');
  await go(`${base}/admin-login.html?return=${encodeURIComponent(`admin.html?application=${reference}`)}`,1200);await evaluate(`document.querySelector('#admin-email').value='admin@masjidpoint.co.uk';document.querySelector('#admin-password').value='Admin!2026Secure';document.querySelector('#admin-login-form').requestSubmit()`);const drawerOpen=()=>evaluate(`document.querySelector('#drawer-title')?.textContent===${JSON.stringify(name)}`);for(let i=0;i<25&&!(await drawerOpen());i++)await sleep(400);assert(await drawerOpen(),'Application did not open in admin review');await click('#approve-application');await sleep(900);
  await go(`${base}/status.html?reference=${encodeURIComponent(reference)}&email=${encodeURIComponent(email)}&e2e=${stamp}`,2500);assert(await evaluate(`document.querySelector('#result-pill')?.textContent.trim().toLowerCase()==='approved'`),'Status page did not show approved');const activationHref=await evaluate(`document.querySelector('#result-action a')?.href`);assert(activationHref?.includes('activate'),'Activation link missing');
  await go(activationHref,1800);await click('#email-form button[type=submit]');await evaluate(`(()=>{const d='123456';document.querySelectorAll('.otp-group input').forEach((e,i)=>e.value=d[i])})()`);await click('#otp-form button[type=submit]');await evaluate(`(()=>{const p=${JSON.stringify(password)};for(const id of ['new-password','confirm-password']){const e=document.getElementById(id);e.value=p;e.dispatchEvent(new Event('input',{bubbles:true}))}})()`);await click('#password-form button[type=submit]');await sleep(900);assert(await evaluate(`!document.querySelector('#activation-success').hidden`),'Activation success was not displayed');
  await go(`${base}/login.html?e2e=${stamp}`,1800);await set('email',email);await set('password',password);await click('#login-form button[type=submit]');await sleep(2200);assert((await evaluate('location.pathname')).match(/\/masjid-portal(?:\.html)?$/),'Login did not reach the mosque portal');assert(await evaluate(`document.querySelector('.masjid-identity strong')?.textContent===${JSON.stringify(name)}`),'Portal showed another mosque identity');assert(await evaluate(`document.querySelector('#approved-count')?.textContent==='0'`),'New mosque inherited approved businesses');
  console.log(JSON.stringify({passed:true,name,reference,email,password,finalUrl:await evaluate('location.href'),checks:['frontend registration','admin UI approval','frontend status approved','OTP activation','password creation','frontend login','isolated mosque portal']},null,2));
})().catch(e=>{console.error(e.stack);process.exitCode=1}).finally(async()=>{try{ws?.close()}catch{}try{browser?.kill()}catch{}});
