const fs=require('fs'),path=require('path'),nodemailer=require('nodemailer');
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
class EmailService{
 // outboxDir lets the caller say where undelivered mail is written. Without it this joined
 // root/data, which ignored a configured data directory: every test suite with a store of
 // its own still wrote its emails into the repository's.
 constructor(root,outboxDir){this.root=root;this.outboxDir=outboxDir||path.join(root,'data','email-outbox');this.base=(process.env.APP_BASE_URL||`http://127.0.0.1:${process.env.PORT||4173}`).replace(/\/$/,'');this.from=process.env.EMAIL_FROM||'MasjidPoint <no-reply@masjidpoint.co.uk>';this.production=process.env.NODE_ENV==='production';this.enabled=Boolean(process.env.SMTP_HOST);this.transport=this.enabled?nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==='true',auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}:undefined}):null}
 async init(){if(this.production&&!this.enabled)throw Error('SMTP_HOST is required in production.');if(this.transport&&process.env.SMTP_VERIFY==='true')await this.transport.verify()}
 html({heading,intro,body,buttonLabel,buttonUrl}){return`<!doctype html><html><body style="margin:0;background:#f5f1e8;color:#173e35;font-family:Arial,sans-serif"><table role="presentation" width="100%"><tr><td align="center" style="padding:36px 16px"><table role="presentation" width="600" style="max-width:600px;background:#fffdf8;border:1px solid #d9dfda"><tr><td style="background:#123f35;padding:24px 34px;color:white;font-size:23px;font-weight:bold">Masjid<span style="color:#d9b467">Point</span></td></tr><tr><td style="padding:38px 34px"><div style="color:#b88432;letter-spacing:2px;font-size:11px;text-transform:uppercase">Community platform</div><h1 style="font-family:Georgia,serif;font-size:34px;margin:12px 0;color:#123f35">${escape(heading)}</h1><p style="line-height:1.7;color:#586b65">${escape(intro)}</p>${body?`<div style="padding:18px;background:#f5f1e8;line-height:1.6">${body}</div>`:''}${buttonUrl?`<p style="margin:28px 0"><a href="${escape(buttonUrl)}" style="display:inline-block;background:#123f35;color:#ffffff!important;border:2px solid #123f35;border-radius:4px;padding:14px 22px;text-decoration:none;font-weight:bold">${escape(buttonLabel||'Open MasjidPoint')} →</a></p><p style="font-size:13px;line-height:1.6;color:#586b65;margin:0 0 6px">If the button does not work, copy this address into your browser:</p><p style="font-size:13px;line-height:1.5;margin:0;word-break:break-all"><a href="${escape(buttonUrl)}" style="color:#0b5c49;text-decoration:underline">${escape(buttonUrl)}</a></p>`:''}<p style="font-size:12px;color:#7a8984;margin-top:30px">If you did not expect this message, contact the MasjidPoint administrator.</p></td></tr></table></td></tr></table></body></html>`}
 async send({to,subject,...content}){if(!to||to==='Registered contact email')return false;const message={from:this.from,to,subject,text:`${content.heading}\n\n${content.intro}\n\n${content.buttonUrl||''}`,html:this.html(content)};if(this.transport){await this.transport.sendMail(message);return true}const dir=this.outboxDir;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,`${Date.now()}-${Math.random().toString(36).slice(2,7)}.json`),JSON.stringify({...message,createdAt:new Date().toISOString()},null,2));return true}
 // The approval email used to carry a verification code. It expired in ten minutes while the
 // link beside it lasted forty-eight hours, and starting the activation issued a fresh code —
 // which invalidated this one. So the recipient got two emails and the code in the first was
 // already dead: 'the verification code is incorrect', for doing exactly as they were told.
 // This says they are approved and sends them to the page. The code arrives when it is needed.
 approval(app,token,code){return this.send({to:app.email,subject:'Your MasjidPoint application is approved',heading:'Alhamdulillah, your application is approved',intro:`${app.name} has been approved by the MasjidPoint administrator. Open the link below to verify your email address and set your password.`,buttonLabel:'Activate your account',buttonUrl:`${this.base}/activate?email=${encodeURIComponent(app.email)}&reference=${encodeURIComponent(app.reference)}`})}
 rejection(app){return this.send({to:app.email,subject:`Update on your ${app.type} application`,heading:'Application update',intro:`We are unable to approve ${app.name} at this time.`,body:app.note?`<strong>Administrator note:</strong><br>${escape(app.note)}`:'You may contact the administrator for further information.',buttonLabel:'Check application status',buttonUrl:`${this.base}/status?reference=${encodeURIComponent(app.reference)}&email=${encodeURIComponent(app.email)}`})}
 payment(to,name,approved,note){return this.send({to,subject:`Payment evidence ${approved?'approved':'requires attention'}`,heading:approved?'Payment verified':'Payment evidence rejected',intro:approved?`The payment submitted by ${name} has been verified.`:`The payment evidence submitted by ${name} could not be verified.`,body:note?`<strong>Administrator note:</strong><br>${escape(note)}`:'',buttonLabel:approved?'View payments':'Resubmit evidence',buttonUrl:`${this.base}/business-portal#payments`})}
 settlement(to,masjid,amount){return this.send({to,subject:'Masjid settlement sent',heading:'Settlement transferred',intro:`MasjidPoint has recorded a £${Number(amount).toFixed(2)} settlement for ${masjid}.`,body:'Please compare this transfer with your mosque bank account and contact the administrator if it does not arrive.',buttonLabel:'View settlements',buttonUrl:`${this.base}/masjid-portal#settlements`})}
 verificationCode(to,code){return this.send({to,subject:`${code} is your MasjidPoint verification code`,heading:'Verify your email address',intro:'Use the secure code below to continue with your MasjidPoint account. It expires in 10 minutes and can be used only once.',body:`<div style="text-align:center;padding:10px 0"><div style="font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#7a8984">Your verification code</div><div style="font-family:Georgia,serif;font-size:38px;font-weight:bold;letter-spacing:10px;color:#123f35;margin:14px 0">${escape(code)}</div><div style="font-size:12px;color:#7a8984">Never share this code with anyone.</div></div>`})}
 reset(to,name,token){return this.send({to,subject:'Reset your MasjidPoint password',heading:'Password reset requested',intro:`A password reset was requested for ${name}. This link expires in 30 minutes and can be used only once.`,buttonLabel:'Reset password',buttonUrl:`${this.base}/reset-password?token=${encodeURIComponent(token)}`})}
}module.exports={EmailService};
