const PDFDocument = require('pdfkit');
const fulfilment = require('./shop-fulfilment');

const money = value => `£${Number(value || 0).toFixed(2)}`;

// A per-order invoice for a mosque shop purchase. Deliberately states the fulfilment and
// payment method on its face so a mosque reading it knows how the customer paid and whether
// the order ever passed through the mosque at all.
function shopInvoicePdf(res, order) {
  const method = fulfilment.methodOf(order);
  const doc = new PDFDocument({ size: 'A4', margin: 52, info: { Title: `Invoice ${order.invoiceNumber}`, Author: 'MasjidPoint' } });
  res.writeHead(200, {
    'Content-Type': 'application/pdf',
    'Content-Disposition': `attachment; filename="${order.invoiceNumber || order.id}.pdf"`,
    'Cache-Control': 'private, no-store'
  });
  doc.pipe(res);
  doc.rect(0, 0, 595, 110).fill('#123f35');
  doc.fillColor('#ffffff').fontSize(26).text('MasjidPoint', 52, 38);
  doc.fontSize(11).text('Mosque community shop', 52, 74);
  doc.fillColor('#123f35').fontSize(28).text('INVOICE', 52, 145);
  doc.fontSize(11).fillColor('#566a64').text(order.invoiceNumber || order.id, 52, 182);

  doc.fillColor('#173e35').fontSize(12)
    .text(`Customer: ${order.customer?.name || 'Customer'}`, 52, 225)
    .text(order.customer?.email || '', 52, 244)
    .text(order.customer?.phone || '', 52, 263)
    .text(`Order: ${order.id}`, 350, 225)
    .text(`Placed: ${new Date(order.placedAt || Date.now()).toLocaleDateString('en-GB')}`, 350, 244)
    .text(`Mosque: ${order.collectionMasjidName || '—'}`, 350, 263);

  doc.fontSize(11).fillColor('#1d5d4e').text(`Fulfilment: ${method.label}`, 52, 296);
  doc.fillColor('#566a64').text(`Payment: ${fulfilment.paymentLabel(order)}  ·  Reference ${order.paymentReference || order.id}`, 52, 314);
  let y = 340;
  const address = fulfilment.addressLines(order);
  if (address.length) {
    doc.fillColor('#173e35').fontSize(10).text(`Deliver to: ${address.join(', ')}`, 52, y, { width: 491 });
    y += 26;
  }

  doc.fontSize(10).fillColor('#ffffff').rect(52, y, 491, 28).fill('#1d5d4e')
    .text('Item', 62, y + 9).text('Qty', 350, y + 9).text('Amount', 470, y + 9);
  y += 40;
  for (const item of order.items || []) {
    doc.fillColor('#173e35')
      .text(item.name || 'Product', 62, y, { width: 270 })
      .text(String(item.quantity || 0), 350, y)
      .text(money(Number(item.price || 0) * Number(item.quantity || 0)), 470, y);
    y += 30;
    if (y > 680) { doc.addPage(); y = 60; }
  }
  if (Number(order.deliveryFee) > 0) {
    doc.fillColor('#173e35').text('Delivery', 62, y, { width: 270 }).text('1', 350, y).text(money(order.deliveryFee), 470, y);
    y += 30;
  }

  doc.moveTo(350, y + 12).lineTo(543, y + 12).stroke('#b4c2ba');
  doc.fontSize(16).fillColor('#123f35').text(`Total  ${money(order.total)}`, 350, y + 28, { align: 'right', width: 193 });
  doc.fontSize(10).fillColor('#687a75')
    .text(`Mosque share: ${money(order.mosqueRevenue)}`, 350, y + 55, { align: 'right', width: 193 });
  doc.fontSize(9).text(
    method.paysUpfront
      ? 'Generated by MasjidPoint. Please quote the payment reference with your bank transfer.'
      : 'Generated by MasjidPoint. This order is payable to the mosque on collection.',
    52, 760, { width: 491, align: 'center' }
  );
  doc.end();
}

module.exports = { shopInvoicePdf };
